/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param id 
 * @param competitorId 
 * @param name 
 * @param domain Bare (scheme-less) domain
 */


data class Actor (

    @Json(name = "type")
    val type: Actor.Type? = null,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "competitor_id")
    val competitorId: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Bare (scheme-less) domain */
    @Json(name = "domain")
    val domain: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: project,competitor
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "project") project("project"),
        @Json(name = "competitor") competitor("competitor");
    }

}

