/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.AiOrdersResponseBySourceInner
import ai.llmpulse.sdk.models.AiOrdersResponseSeriesInner
import ai.llmpulse.sdk.models.AiOrdersResponseTotals

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param platform 
 * @param currency ISO 4217 code of the most recent stored day; null when the window holds no stored order
 * @param from 
 * @param to 
 * @param totals 
 * @param bySource One row per AI assistant, highest revenue first
 * @param series Days that have stored orders, oldest first
 * @param requestId 
 */


data class AiOrdersResponse (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "platform")
    val platform: kotlin.String,

    /* ISO 4217 code of the most recent stored day; null when the window holds no stored order */
    @Json(name = "currency")
    val currency: kotlin.String?,

    @Json(name = "from")
    val from: java.time.LocalDate,

    @Json(name = "to")
    val to: java.time.LocalDate,

    @Json(name = "totals")
    val totals: AiOrdersResponseTotals,

    /* One row per AI assistant, highest revenue first */
    @Json(name = "by_source")
    val bySource: kotlin.collections.List<AiOrdersResponseBySourceInner>,

    /* Days that have stored orders, oldest first */
    @Json(name = "series")
    val series: kotlin.collections.List<AiOrdersResponseSeriesInner>,

    @Json(name = "request_id")
    val requestId: kotlin.String

) {


}

