/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param annotationDate 
 * @param description 
 * @param color Hex color such as '#4F46E5'
 * @param annotationCategoryId 
 */


data class AnnotationCreateResponseAnnotation (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "annotation_date")
    val annotationDate: java.time.LocalDate,

    @Json(name = "description")
    val description: kotlin.String?,

    /* Hex color such as '#4F46E5' */
    @Json(name = "color")
    val color: kotlin.String?,

    @Json(name = "annotation_category_id")
    val annotationCategoryId: kotlin.Int?

) {


}

