/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.AnswerDetailsLocale

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param promptId 
 * @param promptText 
 * @param model 
 * @param response 
 * @param responseTruncated 
 * @param executedAt 
 * @param durationMs 
 * @param success 
 * @param fanOutQueries 
 * @param mentions 
 * @param citations 
 * @param competitorMentions 
 * @param competitorCitations 
 * @param sentiments 
 * @param sources 
 * @param shoppingProducts 
 * @param brandEntities 
 * @param localBusinesses 
 * @param locale 
 * @param appUrl Opens this answer in the app. The link names its project, so it opens there for any user with access to that project
 */


data class AnswerDetails (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "prompt_id")
    val promptId: kotlin.Int? = null,

    @Json(name = "prompt_text")
    val promptText: kotlin.String? = null,

    @Json(name = "model")
    val model: kotlin.String? = null,

    @Json(name = "response")
    val response: kotlin.String? = null,

    @Json(name = "response_truncated")
    val responseTruncated: kotlin.Boolean? = null,

    @Json(name = "executed_at")
    val executedAt: java.time.OffsetDateTime? = null,

    @Json(name = "duration_ms")
    val durationMs: kotlin.Int? = null,

    @Json(name = "success")
    val success: kotlin.Boolean? = null,

    @Json(name = "fan_out_queries")
    val fanOutQueries: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "mentions")
    val mentions: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "citations")
    val citations: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "competitor_mentions")
    val competitorMentions: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "competitor_citations")
    val competitorCitations: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "sentiments")
    val sentiments: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "sources")
    val sources: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "shopping_products")
    val shoppingProducts: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "brand_entities")
    val brandEntities: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "local_businesses")
    val localBusinesses: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "locale")
    val locale: AnswerDetailsLocale? = null,

    /* Opens this answer in the app. The link names its project, so it opens there for any user with access to that project */
    @Json(name = "app_url")
    val appUrl: java.net.URI? = null

) {


}

