/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The catalog product the suggestion was written for
 *
 * @param externalId The store's product id, e.g. gid://shopify/Product/1
 * @param handle 
 * @param title 
 */


data class CatalogPromptSuggestionProduct (

    /* The store's product id, e.g. gid://shopify/Product/1 */
    @Json(name = "external_id")
    val externalId: kotlin.String? = null,

    @Json(name = "handle")
    val handle: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null

) {


}

