/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.CatalogPromptSuggestionsAcceptResponseAcceptedInner
import ai.llmpulse.sdk.models.CatalogPromptSuggestionsAcceptResponseSkippedInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param accepted 
 * @param skipped 
 * @param promptsAvailable Prompt slots left on the plan; null when unlimited
 * @param requestId 
 */


data class CatalogPromptSuggestionsAcceptResponse (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "accepted")
    val accepted: kotlin.collections.List<CatalogPromptSuggestionsAcceptResponseAcceptedInner>,

    @Json(name = "skipped")
    val skipped: kotlin.collections.List<CatalogPromptSuggestionsAcceptResponseSkippedInner>,

    /* Prompt slots left on the plan; null when unlimited */
    @Json(name = "prompts_available")
    val promptsAvailable: kotlin.Int?,

    @Json(name = "request_id")
    val requestId: kotlin.String

) {


}

