/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.CatalogPromptSuggestion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param created 
 * @param skipped Generated prompts not saved because the project already holds them as a suggestion (from any source or product, in any status).
 * @param `data` 
 * @param requestId 
 */


data class CatalogPromptSuggestionsCreateResponse (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "created")
    val created: kotlin.Int,

    /* Generated prompts not saved because the project already holds them as a suggestion (from any source or product, in any status). */
    @Json(name = "skipped")
    val skipped: kotlin.Int,

    @Json(name = "data")
    val `data`: kotlin.collections.List<CatalogPromptSuggestion>,

    @Json(name = "request_id")
    val requestId: kotlin.String

) {


}

