/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.CatalogProduct

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param platform 
 * @param products 
 * @param countryCode Defaults to the project country
 * @param languageCode Defaults to the project language
 */


data class CatalogPromptSuggestionsCreateRequest (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "platform")
    val platform: CatalogPromptSuggestionsCreateRequest.Platform,

    @Json(name = "products")
    val products: kotlin.collections.List<CatalogProduct>,

    /* Defaults to the project country */
    @Json(name = "country_code")
    val countryCode: kotlin.String? = null,

    /* Defaults to the project language */
    @Json(name = "language_code")
    val languageCode: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: shopify
     */
    @JsonClass(generateAdapter = false)
    enum class Platform(val value: kotlin.String) {
        @Json(name = "shopify") shopify("shopify");
    }

}

