/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param suggestionId 
 * @param reason accepted or rejected (the suggestion was no longer pending), or pending_deletion
 */


data class CatalogPromptSuggestionsAcceptResponseSkippedInner (

    @Json(name = "suggestion_id")
    val suggestionId: kotlin.Int,

    /* accepted or rejected (the suggestion was no longer pending), or pending_deletion */
    @Json(name = "reason")
    val reason: kotlin.String

) {


}

