/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.CollectionCreateResponseCollection

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param collection 
 * @param promptsAttached Existing prompts attached through prompt_ids
 * @param totalCollections 
 * @param requestId 
 */


data class CollectionCreateResponse (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "collection")
    val collection: CollectionCreateResponseCollection,

    /* Existing prompts attached through prompt_ids */
    @Json(name = "prompts_attached")
    val promptsAttached: kotlin.Int,

    @Json(name = "total_collections")
    val totalCollections: kotlin.Int,

    @Json(name = "request_id")
    val requestId: kotlin.String

) {


}

