/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.CitationMatchMode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param domain Bare (scheme-less) domain. Null only on the own-brand row (include_project_brand=true) when the project has no URL.
 * @param matchingNames Alternative names matched as this competitor. Absent on the own-brand row
 * @param citationMatchMode 
 * @param citationMatchPath Set only when citation_match_mode is path_prefix
 * @param actorType Only present when include_project_brand=true
 * @param isOwn Only present when include_project_brand=true
 */


data class Competitor (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Bare (scheme-less) domain. Null only on the own-brand row (include_project_brand=true) when the project has no URL. */
    @Json(name = "domain")
    val domain: kotlin.String? = null,

    /* Alternative names matched as this competitor. Absent on the own-brand row */
    @Json(name = "matching_names")
    val matchingNames: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "citation_match_mode")
    val citationMatchMode: CitationMatchMode? = null,

    /* Set only when citation_match_mode is path_prefix */
    @Json(name = "citation_match_path")
    val citationMatchPath: kotlin.String? = null,

    /* Only present when include_project_brand=true */
    @Json(name = "actor_type")
    val actorType: Competitor.ActorType? = null,

    /* Only present when include_project_brand=true */
    @Json(name = "is_own")
    val isOwn: kotlin.Boolean? = null

) {

    /**
     * Only present when include_project_brand=true
     *
     * Values: project,competitor
     */
    @JsonClass(generateAdapter = false)
    enum class ActorType(val value: kotlin.String) {
        @Json(name = "project") project("project"),
        @Json(name = "competitor") competitor("competitor");
    }

}

