/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param brandName 
 * @param domain URL is accepted and normalised to host (e.g. https://www.openai.com → openai.com)
 * @param matchingNames 
 */


data class CreateCompetitorRequest (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "brand_name")
    val brandName: kotlin.String,

    /* URL is accepted and normalised to host (e.g. https://www.openai.com → openai.com) */
    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "matching_names")
    val matchingNames: kotlin.collections.List<kotlin.String>? = null

) {


}

