/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param weeklyEmailSubscribed 
 * @param executePromptsImmediately 
 */


data class FinalizeProjectDraftRequest (

    @Json(name = "weekly_email_subscribed")
    val weeklyEmailSubscribed: kotlin.Boolean? = null,

    @Json(name = "execute_prompts_immediately")
    val executePromptsImmediately: kotlin.Boolean? = null

) {


}

