/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accepted true accepts the issue (it stays listed but leaves the open count until its evidence changes); false reopens it
 * @param projectId 
 */


data class GeoAuditIssueUpdateRequest (

    /* true accepts the issue (it stays listed but leaves the open count until its evidence changes); false reopens it */
    @Json(name = "accepted")
    val accepted: kotlin.Boolean,

    @Json(name = "project_id")
    val projectId: kotlin.Int? = null

) {


}

