/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.GeoAuditComparisonChangesInner
import ai.llmpulse.sdk.models.GeoAuditRun

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param fromRun 
 * @param toRun 
 * @param comparable 
 * @param scoreDelta 
 * @param metricDeltas 
 * @param counts 
 * @param changes 
 * @param requestId 
 */


data class GeoAuditComparison (

    @Json(name = "project_id")
    val projectId: kotlin.Int? = null,

    @Json(name = "from_run")
    val fromRun: GeoAuditRun? = null,

    @Json(name = "to_run")
    val toRun: GeoAuditRun? = null,

    @Json(name = "comparable")
    val comparable: kotlin.Boolean? = null,

    @Json(name = "score_delta")
    val scoreDelta: java.math.BigDecimal? = null,

    @Json(name = "metric_deltas")
    val metricDeltas: kotlin.collections.Map<kotlin.String, java.math.BigDecimal>? = null,

    @Json(name = "counts")
    val counts: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,

    @Json(name = "changes")
    val changes: kotlin.collections.List<GeoAuditComparisonChangesInner>? = null,

    @Json(name = "request_id")
    val requestId: kotlin.String? = null

) {


}

