/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param id 
 * @param archived 
 * @param requestId 
 */


data class GeoAuditArchived (

    @Json(name = "project_id")
    val projectId: kotlin.Int? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "archived")
    val archived: kotlin.Boolean? = null,

    @Json(name = "request_id")
    val requestId: kotlin.String? = null

) {


}

