/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param checkKey 
 * @param checkTitle 
 * @param subjectKey 
 * @param subject 
 * @param severity 
 * @param state 
 * @param badge How the latest comparable run moved the issue
 * @param accepted 
 * @param acceptedAt 
 * @param regressionCount 
 * @param evidence 
 * @param updatedAt 
 */


data class GeoAuditIssue (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "check_key")
    val checkKey: kotlin.String? = null,

    @Json(name = "check_title")
    val checkTitle: kotlin.String? = null,

    @Json(name = "subject_key")
    val subjectKey: kotlin.String? = null,

    @Json(name = "subject")
    val subject: kotlin.String? = null,

    @Json(name = "severity")
    val severity: kotlin.String? = null,

    @Json(name = "state")
    val state: GeoAuditIssue.State? = null,

    /* How the latest comparable run moved the issue */
    @Json(name = "badge")
    val badge: GeoAuditIssue.Badge? = null,

    @Json(name = "accepted")
    val accepted: kotlin.Boolean? = null,

    @Json(name = "accepted_at")
    val acceptedAt: java.time.OffsetDateTime? = null,

    @Json(name = "regression_count")
    val regressionCount: kotlin.Int? = null,

    @Json(name = "evidence")
    val evidence: kotlin.Any? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: `open`,fixed,gone
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "open") `open`("open"),
        @Json(name = "fixed") fixed("fixed"),
        @Json(name = "gone") gone("gone");
    }
    /**
     * How the latest comparable run moved the issue
     *
     * Values: new,persisting,regressed,fixed,gone
     */
    @JsonClass(generateAdapter = false)
    enum class Badge(val value: kotlin.String) {
        @Json(name = "new") new("new"),
        @Json(name = "persisting") persisting("persisting"),
        @Json(name = "regressed") regressed("regressed"),
        @Json(name = "fixed") fixed("fixed"),
        @Json(name = "gone") gone("gone");
    }

}

