/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One run of an audit. Null where an audit has no run yet (latest_run) or a comparison has no earlier run (from_run).
 *
 * @param sequence Run number within the audit, starting at 1
 * @param status 
 * @param trigger 
 * @param score 
 * @param grade 
 * @param scoreDelta Score change against the previous completed run
 * @param comparableToPrevious False when the checks or the audit settings changed since the previous run, so a diff may reflect that change
 * @param newIssues 
 * @param fixedIssues 
 * @param regressedIssues 
 * @param error 
 * @param engineVersion 
 * @param createdAt 
 * @param finishedAt 
 * @param appUrl 
 */


data class GeoAuditRun (

    /* Run number within the audit, starting at 1 */
    @Json(name = "sequence")
    val sequence: kotlin.Int? = null,

    @Json(name = "status")
    val status: GeoAuditRun.Status? = null,

    @Json(name = "trigger")
    val trigger: GeoAuditRun.Trigger? = null,

    @Json(name = "score")
    val score: java.math.BigDecimal? = null,

    @Json(name = "grade")
    val grade: kotlin.String? = null,

    /* Score change against the previous completed run */
    @Json(name = "score_delta")
    val scoreDelta: java.math.BigDecimal? = null,

    /* False when the checks or the audit settings changed since the previous run, so a diff may reflect that change */
    @Json(name = "comparable_to_previous")
    val comparableToPrevious: kotlin.Boolean? = null,

    @Json(name = "new_issues")
    val newIssues: kotlin.Int? = null,

    @Json(name = "fixed_issues")
    val fixedIssues: kotlin.Int? = null,

    @Json(name = "regressed_issues")
    val regressedIssues: kotlin.Int? = null,

    @Json(name = "error")
    val error: kotlin.String? = null,

    @Json(name = "engine_version")
    val engineVersion: kotlin.String? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "finished_at")
    val finishedAt: java.time.OffsetDateTime? = null,

    @Json(name = "app_url")
    val appUrl: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: queued,running,completed,failed,unreachable
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "queued") queued("queued"),
        @Json(name = "running") running("running"),
        @Json(name = "completed") completed("completed"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "unreachable") unreachable("unreachable");
    }
    /**
     * 
     *
     * Values: scheduled,manual,api,mcp,legacy_import
     */
    @JsonClass(generateAdapter = false)
    enum class Trigger(val value: kotlin.String) {
        @Json(name = "scheduled") scheduled("scheduled"),
        @Json(name = "manual") manual("manual"),
        @Json(name = "api") api("api"),
        @Json(name = "mcp") mcp("mcp"),
        @Json(name = "legacy_import") legacy_import("legacy_import");
    }

}

