/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.GeoAuditRun
import ai.llmpulse.sdk.models.GeoAuditSchedule

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Stable audit id
 * @param auditType 
 * @param target The audited domain (site-wide types) or page URL, normalized
 * @param countryCode 
 * @param cadence 
 * @param status 
 * @param pausedReason user, or unreachable when three runs in a row could not reach the site
 * @param schedule 
 * @param nextRunAt 
 * @param emailAlerts 
 * @param recurringAvailable Whether this audit type can run weekly or monthly
 * @param checksTracked Whether runs of this type produce findings and issues, or a score only
 * @param latestRun 
 * @param openIssues 
 * @param openCriticalIssues 
 * @param createdAt 
 * @param appUrl 
 * @param projectId 
 * @param requestId 
 */


data class GeoAuditResponse (

    /* Stable audit id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "audit_type")
    val auditType: GeoAuditResponse.AuditType? = null,

    /* The audited domain (site-wide types) or page URL, normalized */
    @Json(name = "target")
    val target: kotlin.String? = null,

    @Json(name = "country_code")
    val countryCode: kotlin.String? = null,

    @Json(name = "cadence")
    val cadence: GeoAuditResponse.Cadence? = null,

    @Json(name = "status")
    val status: GeoAuditResponse.Status? = null,

    /* user, or unreachable when three runs in a row could not reach the site */
    @Json(name = "paused_reason")
    val pausedReason: kotlin.String? = null,

    @Json(name = "schedule")
    val schedule: GeoAuditSchedule? = null,

    @Json(name = "next_run_at")
    val nextRunAt: java.time.OffsetDateTime? = null,

    @Json(name = "email_alerts")
    val emailAlerts: kotlin.Boolean? = null,

    /* Whether this audit type can run weekly or monthly */
    @Json(name = "recurring_available")
    val recurringAvailable: kotlin.Boolean? = null,

    /* Whether runs of this type produce findings and issues, or a score only */
    @Json(name = "checks_tracked")
    val checksTracked: kotlin.Boolean? = null,

    @Json(name = "latest_run")
    val latestRun: GeoAuditRun? = null,

    @Json(name = "open_issues")
    val openIssues: kotlin.Int? = null,

    @Json(name = "open_critical_issues")
    val openCriticalIssues: kotlin.Int? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "app_url")
    val appUrl: kotlin.String? = null,

    @Json(name = "project_id")
    val projectId: kotlin.Int? = null,

    @Json(name = "request_id")
    val requestId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: agent_readiness,robots_txt,crawlability,schema,content_readiness,discoverability,site_structure
     */
    @JsonClass(generateAdapter = false)
    enum class AuditType(val value: kotlin.String) {
        @Json(name = "agent_readiness") agent_readiness("agent_readiness"),
        @Json(name = "robots_txt") robots_txt("robots_txt"),
        @Json(name = "crawlability") crawlability("crawlability"),
        @Json(name = "schema") schema("schema"),
        @Json(name = "content_readiness") content_readiness("content_readiness"),
        @Json(name = "discoverability") discoverability("discoverability"),
        @Json(name = "site_structure") site_structure("site_structure");
    }
    /**
     * 
     *
     * Values: once,weekly,monthly
     */
    @JsonClass(generateAdapter = false)
    enum class Cadence(val value: kotlin.String) {
        @Json(name = "once") once("once"),
        @Json(name = "weekly") weekly("weekly"),
        @Json(name = "monthly") monthly("monthly");
    }
    /**
     * 
     *
     * Values: active,paused,archived
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "active") active("active"),
        @Json(name = "paused") paused("paused"),
        @Json(name = "archived") archived("archived");
    }

}

