/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param checkKey Stable key of the check within its audit type
 * @param checkTitle 
 * @param subjectKey What the check is about (site for site-wide checks, a bot slug for robots.txt bot checks)
 * @param subject 
 * @param status 
 * @param severity 
 * @param evidence 
 */


data class GeoAuditFinding (

    /* Stable key of the check within its audit type */
    @Json(name = "check_key")
    val checkKey: kotlin.String? = null,

    @Json(name = "check_title")
    val checkTitle: kotlin.String? = null,

    /* What the check is about (site for site-wide checks, a bot slug for robots.txt bot checks) */
    @Json(name = "subject_key")
    val subjectKey: kotlin.String? = null,

    @Json(name = "subject")
    val subject: kotlin.String? = null,

    @Json(name = "status")
    val status: GeoAuditFinding.Status? = null,

    @Json(name = "severity")
    val severity: GeoAuditFinding.Severity? = null,

    @Json(name = "evidence")
    val evidence: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: pass,warn,fail,info,not_applicable,unknown
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "pass") pass("pass"),
        @Json(name = "warn") warn("warn"),
        @Json(name = "fail") fail("fail"),
        @Json(name = "info") info("info"),
        @Json(name = "not_applicable") not_applicable("not_applicable"),
        @Json(name = "unknown") unknown("unknown");
    }
    /**
     * 
     *
     * Values: critical,high,medium,low,info
     */
    @JsonClass(generateAdapter = false)
    enum class Severity(val value: kotlin.String) {
        @Json(name = "critical") critical("critical"),
        @Json(name = "high") high("high"),
        @Json(name = "medium") medium("medium"),
        @Json(name = "low") low("low"),
        @Json(name = "info") info("info");
    }

}

