/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestsPerMinute The ceiling enforced for the API key used on this call, which may be above the 300/min default.
 * @param writeRequestsPerMinute Flat ceiling on write requests, the same for every key.
 */


data class GetAccount200ResponseRateLimits (

    /* The ceiling enforced for the API key used on this call, which may be above the 300/min default. */
    @Json(name = "requests_per_minute")
    val requestsPerMinute: kotlin.Int? = null,

    /* Flat ceiling on write requests, the same for every key. */
    @Json(name = "write_requests_per_minute")
    val writeRequestsPerMinute: kotlin.Int? = null

) {


}

