/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param taskType 
 * @param promptId 
 * @param customTopic 
 * @param userInstructions 
 * @param outputLanguageCode 
 * @param existingContent 
 * @param existingContentUrl 
 */


data class IntelligenceTaskCreateRequest (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "task_type")
    val taskType: IntelligenceTaskCreateRequest.TaskType,

    @Json(name = "prompt_id")
    val promptId: kotlin.Int? = null,

    @Json(name = "custom_topic")
    val customTopic: kotlin.String? = null,

    @Json(name = "user_instructions")
    val userInstructions: kotlin.String? = null,

    @Json(name = "output_language_code")
    val outputLanguageCode: kotlin.String? = null,

    @Json(name = "existing_content")
    val existingContent: kotlin.String? = null,

    @Json(name = "existing_content_url")
    val existingContentUrl: java.net.URI? = null

) {

    /**
     * 
     *
     * Values: brief,create,update,pr_insights,custom
     */
    @JsonClass(generateAdapter = false)
    enum class TaskType(val value: kotlin.String) {
        @Json(name = "brief") brief("brief"),
        @Json(name = "create") create("create"),
        @Json(name = "update") update("update"),
        @Json(name = "pr_insights") pr_insights("pr_insights"),
        @Json(name = "custom") custom("custom");
    }

}

