/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.LlmsTxtTechnicalGeoReportResultData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An llms_txt technical GEO report with its files, in the shape GET /technical_geo_reports/{id} returns
 *
 * @param id 
 * @param reportType Always llms_txt
 * @param projectId 
 * @param batchId Bundle the report was created in; null for a report created on its own
 * @param url Always null for llms_txt reports; domain names the website
 * @param domain 
 * @param countryCode 
 * @param outputLanguageCode ISO 639-1 code the files were requested in; null when they are written in the website's own language
 * @param status 
 * @param resultAvailable 
 * @param overallScore Always null for llms_txt reports
 * @param createdAt 
 * @param updatedAt 
 * @param resultData 
 * @param errorMessage 
 * @param pollAfterSeconds Seconds to wait before polling again while the report runs; null once it has finished
 * @param appUrl Opens this report in the app
 * @param requestId 
 */


data class LlmsTxtTechnicalGeoReport (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* Always llms_txt */
    @Json(name = "report_type")
    val reportType: kotlin.String? = null,

    @Json(name = "project_id")
    val projectId: kotlin.Int? = null,

    /* Bundle the report was created in; null for a report created on its own */
    @Json(name = "batch_id")
    val batchId: kotlin.Int? = null,

    /* Always null for llms_txt reports; domain names the website */
    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "domain")
    val domain: kotlin.String? = null,

    @Json(name = "country_code")
    val countryCode: kotlin.String? = null,

    /* ISO 639-1 code the files were requested in; null when they are written in the website's own language */
    @Json(name = "output_language_code")
    val outputLanguageCode: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "result_available")
    val resultAvailable: kotlin.Boolean? = null,

    /* Always null for llms_txt reports */
    @Json(name = "overall_score")
    val overallScore: java.math.BigDecimal? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "result_data")
    val resultData: LlmsTxtTechnicalGeoReportResultData? = null,

    @Json(name = "error_message")
    val errorMessage: kotlin.String? = null,

    /* Seconds to wait before polling again while the report runs; null once it has finished */
    @Json(name = "poll_after_seconds")
    val pollAfterSeconds: kotlin.Int? = null,

    /* Opens this report in the app */
    @Json(name = "app_url")
    val appUrl: java.net.URI? = null,

    @Json(name = "request_id")
    val requestId: kotlin.String? = null

) {


}

