/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name The project's brand name (its name when no brand name is set)
 * @param promptId 
 * @param promptExecutionId 
 * @param createdAt 
 */


data class MentionRecord (

    @Json(name = "id")
    val id: kotlin.Int,

    /* The project's brand name (its name when no brand name is set) */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "prompt_id")
    val promptId: kotlin.Int,

    @Json(name = "prompt_execution_id")
    val promptExecutionId: kotlin.Int,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}

