/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param models 
 * @param requestId 
 */


data class ModelsResponse (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "models")
    val models: kotlin.collections.List<ModelsResponse.Models>,

    @Json(name = "request_id")
    val requestId: kotlin.String

) {

    /**
     * 
     *
     * Values: chatgpt,perplexity,ai_mode,ai_overview,gemini,copilot,amazon_rufus,claude,grok,deepseek,naver_ai,baidu_ai,meta_ai
     */
    @JsonClass(generateAdapter = false)
    enum class Models(val value: kotlin.String) {
        @Json(name = "chatgpt") chatgpt("chatgpt"),
        @Json(name = "perplexity") perplexity("perplexity"),
        @Json(name = "ai_mode") ai_mode("ai_mode"),
        @Json(name = "ai_overview") ai_overview("ai_overview"),
        @Json(name = "gemini") gemini("gemini"),
        @Json(name = "copilot") copilot("copilot"),
        @Json(name = "amazon_rufus") amazon_rufus("amazon_rufus"),
        @Json(name = "claude") claude("claude"),
        @Json(name = "grok") grok("grok"),
        @Json(name = "deepseek") deepseek("deepseek"),
        @Json(name = "naver_ai") naver_ai("naver_ai"),
        @Json(name = "baidu_ai") baidu_ai("baidu_ai"),
        @Json(name = "meta_ai") meta_ai("meta_ai");
    }

}

