/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Envelope shared by the paginated listings; each listing adds its own data rows
 *
 * @param projectId 
 * @param page 
 * @param perPage 
 * @param total Rows matching the filters across every page
 * @param requestId 
 */


data class PaginatedEnvelope (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "per_page")
    val perPage: kotlin.Int,

    /* Rows matching the filters across every page */
    @Json(name = "total")
    val total: kotlin.Int,

    @Json(name = "request_id")
    val requestId: kotlin.String

) {


}

