/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.ProjectCreateResponseCompetitors
import ai.llmpulse.sdk.models.ProjectCreateResponseEmailSubscription
import ai.llmpulse.sdk.models.ProjectCreateResponseLimits
import ai.llmpulse.sdk.models.ProjectCreateResponsePrompts

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param project Same shape as GET /dimensions/projects/{id}
 * @param prompts 
 * @param competitors 
 * @param emailSubscription 
 * @param limits 
 * @param idempotent Present and true only on external_identifier replays
 * @param requestId 
 */


data class ProjectCreateResponse (

    /* Same shape as GET /dimensions/projects/{id} */
    @Json(name = "project")
    val project: kotlin.Any? = null,

    @Json(name = "prompts")
    val prompts: ProjectCreateResponsePrompts? = null,

    @Json(name = "competitors")
    val competitors: ProjectCreateResponseCompetitors? = null,

    @Json(name = "email_subscription")
    val emailSubscription: ProjectCreateResponseEmailSubscription? = null,

    @Json(name = "limits")
    val limits: ProjectCreateResponseLimits? = null,

    /* Present and true only on external_identifier replays */
    @Json(name = "idempotent")
    val idempotent: kotlin.Boolean? = null,

    @Json(name = "request_id")
    val requestId: kotlin.String? = null

) {


}

