/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Requires Growth plan or above
 *
 * @param youtubeChannelUrl 
 * @param instagramProfileUrl 
 * @param facebookPageUrl 
 * @param tiktokProfileUrl 
 * @param appStoreUrl 
 * @param googlePlayUrl 
 */


data class ProjectCreateRequestOwnedMedia (

    @Json(name = "youtube_channel_url")
    val youtubeChannelUrl: kotlin.String? = null,

    @Json(name = "instagram_profile_url")
    val instagramProfileUrl: kotlin.String? = null,

    @Json(name = "facebook_page_url")
    val facebookPageUrl: kotlin.String? = null,

    @Json(name = "tiktok_profile_url")
    val tiktokProfileUrl: kotlin.String? = null,

    @Json(name = "app_store_url")
    val appStoreUrl: kotlin.String? = null,

    @Json(name = "google_play_url")
    val googlePlayUrl: kotlin.String? = null

) {


}

