/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param created 
 * @param skipped 
 * @param execution 
 */


data class ProjectCreateResponsePrompts (

    @Json(name = "created")
    val created: kotlin.Int? = null,

    @Json(name = "skipped")
    val skipped: kotlin.Int? = null,

    @Json(name = "execution")
    val execution: ProjectCreateResponsePrompts.Execution? = null

) {

    /**
     * 
     *
     * Values: immediate,deferred_to_next_scheduled_run
     */
    @JsonClass(generateAdapter = false)
    enum class Execution(val value: kotlin.String) {
        @Json(name = "immediate") immediate("immediate"),
        @Json(name = "deferred_to_next_scheduled_run") deferred_to_next_scheduled_run("deferred_to_next_scheduled_run");
    }

}

