/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param rawInput 
 * @param status 
 */


data class PromptsCreateResponseDataInner (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "raw_input")
    val rawInput: kotlin.String? = null,

    @Json(name = "status")
    val status: PromptsCreateResponseDataInner.Status? = null

) {

    /**
     * 
     *
     * Values: created,exists
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "created") created("created"),
        @Json(name = "exists") exists("exists");
    }

}

