/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param prompts 
 * @param countryCode 
 * @param languageCode 
 */


data class PromptsCreateRequest (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "prompts")
    val prompts: kotlin.collections.List<kotlin.String>,

    @Json(name = "country_code")
    val countryCode: kotlin.String,

    @Json(name = "language_code")
    val languageCode: kotlin.String

) {


}

