/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.TagRef

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param promptText 
 * @param collectionId Primary tag, when the prompt has one
 * @param collectionIds Every tag the prompt belongs to
 * @param tags 
 * @param countryCode 
 * @param languageCode 
 * @param promptType Search intent: informational, navigational, commercial or transactional. Null until the prompt is classified
 * @param brandKind Brand focus: brand, brand_other or non_brand. Null until the prompt is classified
 * @param lastExecutedAt Null until the prompt has run
 * @param appUrl Opens this prompt in the app. The link names its project, so it opens there for any user with access to that project
 */


data class PromptRecord (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "prompt_text")
    val promptText: kotlin.String,

    /* Primary tag, when the prompt has one */
    @Json(name = "collection_id")
    val collectionId: kotlin.Int?,

    /* Every tag the prompt belongs to */
    @Json(name = "collection_ids")
    val collectionIds: kotlin.collections.List<kotlin.Int>,

    @Json(name = "tags")
    val tags: kotlin.collections.List<TagRef>,

    @Json(name = "country_code")
    val countryCode: kotlin.String?,

    @Json(name = "language_code")
    val languageCode: kotlin.String?,

    /* Search intent: informational, navigational, commercial or transactional. Null until the prompt is classified */
    @Json(name = "prompt_type")
    val promptType: kotlin.String?,

    /* Brand focus: brand, brand_other or non_brand. Null until the prompt is classified */
    @Json(name = "brand_kind")
    val brandKind: kotlin.String?,

    /* Null until the prompt has run */
    @Json(name = "last_executed_at")
    val lastExecutedAt: java.time.OffsetDateTime?,

    /* Opens this prompt in the app. The link names its project, so it opens there for any user with access to that project */
    @Json(name = "app_url")
    val appUrl: java.net.URI

) {


}

