/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.SampleWebhookPayloads200ResponseDataInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param eventType 
 * @param `data` 
 * @param requestId 
 */


data class SampleWebhookPayloads200Response (

    @Json(name = "event_type")
    val eventType: kotlin.String? = null,

    @Json(name = "data")
    val `data`: kotlin.collections.List<SampleWebhookPayloads200ResponseDataInner>? = null,

    @Json(name = "request_id")
    val requestId: kotlin.String? = null

) {


}

