/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.SovResponseBreakdownInner
import ai.llmpulse.sdk.models.SovResponseCurrentInner
import ai.llmpulse.sdk.models.SovResponseOverTimeInner
import ai.llmpulse.sdk.models.SovResponsePeriodsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param periods Per-bucket sample size and completeness: mentions is the total the shares were computed on (1-3 mentions produce the 100/50/33.33 low-sample patterns); partial marks buckets still collecting data or clipped by the requested window.
 * @param overTime 
 * @param current 
 * @param breakdown 
 * @param others 
 */


data class SovResponse (

    @Json(name = "project_id")
    val projectId: kotlin.Int? = null,

    /* Per-bucket sample size and completeness: mentions is the total the shares were computed on (1-3 mentions produce the 100/50/33.33 low-sample patterns); partial marks buckets still collecting data or clipped by the requested window. */
    @Json(name = "periods")
    val periods: kotlin.collections.List<SovResponsePeriodsInner>? = null,

    @Json(name = "over_time")
    val overTime: kotlin.collections.List<SovResponseOverTimeInner>? = null,

    @Json(name = "current")
    val current: kotlin.collections.List<SovResponseCurrentInner>? = null,

    @Json(name = "breakdown")
    val breakdown: kotlin.collections.List<SovResponseBreakdownInner>? = null,

    @Json(name = "others")
    val others: kotlin.collections.List<kotlin.Any>? = null

) {


}

