/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.TechnicalGeoReportContentUpdateRequestEdits

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param reportType Only llms_txt reports have editable content
 * @param contentVersion result_data.content_version of the report as last read. It changes on every save; a value that no longer matches is refused as stale
 * @param edits 
 */


data class TechnicalGeoReportContentUpdateRequest (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    /* Only llms_txt reports have editable content */
    @Json(name = "report_type")
    val reportType: TechnicalGeoReportContentUpdateRequest.ReportType,

    /* result_data.content_version of the report as last read. It changes on every save; a value that no longer matches is refused as stale */
    @Json(name = "content_version")
    val contentVersion: kotlin.String,

    @Json(name = "edits")
    val edits: TechnicalGeoReportContentUpdateRequestEdits

) {

    /**
     * Only llms_txt reports have editable content
     *
     * Values: llms_txt
     */
    @JsonClass(generateAdapter = false)
    enum class ReportType(val value: kotlin.String) {
        @Json(name = "llms_txt") llms_txt("llms_txt");
    }

}

