/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param title 
 * @param description 
 * @param annotationDate 
 * @param color 
 * @param annotationCategoryId 
 */


data class UpdateAnnotationRequest (

    @Json(name = "project_id")
    val projectId: kotlin.Int,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "annotation_date")
    val annotationDate: java.time.LocalDate? = null,

    @Json(name = "color")
    val color: kotlin.String? = null,

    @Json(name = "annotation_category_id")
    val annotationCategoryId: kotlin.Int? = null

) {


}

