/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param kind dimension or metric, when the provider says.
 * @param type The provider's column type, when it says (PostHog).
 * @param label The provider's display label, when it sends one (Piano).
 */


data class WebAnalyticsQueryResponseColumnsInner (

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* dimension or metric, when the provider says. */
    @Json(name = "kind")
    val kind: kotlin.String? = null,

    /* The provider's column type, when it says (PostHog). */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* The provider's display label, when it sends one (Piano). */
    @Json(name = "label")
    val label: kotlin.String? = null

) {


}

