/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param provider The connected web analytics provider.
 * @param `property` The property, site, report suite (rsid:...), data view (dataview:...) or project every query runs on.
 * @param queryLanguage The native query format the provider accepts.
 * @param docsUrl The provider's reference for that format.
 * @param allowedFields Top-level query fields that are forwarded.
 * @param rules What the bridge enforces and the provider's main constraints.
 * @param example A worked query to adapt.
 * @param fields The provider's live field list where it offers one: GA4 dimensions and metrics with custom definitions, Adobe ids, Matomo report methods, PostHog event names, the Plausible catalog. Null when the provider did not return it.
 * @param fieldsUnavailable Present when the field list could not be read; the format and example still apply.
 * @param requestId 
 */


data class WebAnalyticsSchemaResponse (

    @Json(name = "project_id")
    val projectId: kotlin.Int? = null,

    /* The connected web analytics provider. */
    @Json(name = "provider")
    val provider: WebAnalyticsSchemaResponse.Provider? = null,

    /* The property, site, report suite (rsid:...), data view (dataview:...) or project every query runs on. */
    @Json(name = "property")
    val `property`: kotlin.String? = null,

    /* The native query format the provider accepts. */
    @Json(name = "query_language")
    val queryLanguage: kotlin.String? = null,

    /* The provider's reference for that format. */
    @Json(name = "docs_url")
    val docsUrl: kotlin.String? = null,

    /* Top-level query fields that are forwarded. */
    @Json(name = "allowed_fields")
    val allowedFields: kotlin.collections.List<kotlin.String>? = null,

    /* What the bridge enforces and the provider's main constraints. */
    @Json(name = "rules")
    val rules: kotlin.collections.List<kotlin.String>? = null,

    /* A worked query to adapt. */
    @Json(name = "example")
    val example: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* The provider's live field list where it offers one: GA4 dimensions and metrics with custom definitions, Adobe ids, Matomo report methods, PostHog event names, the Plausible catalog. Null when the provider did not return it. */
    @Json(name = "fields")
    val fields: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Present when the field list could not be read; the format and example still apply. */
    @Json(name = "fields_unavailable")
    val fieldsUnavailable: kotlin.String? = null,

    @Json(name = "request_id")
    val requestId: kotlin.String? = null

) {

    /**
     * The connected web analytics provider.
     *
     * Values: google_analytics,adobe_analytics,matomo,posthog,plausible,piano
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "google_analytics") google_analytics("google_analytics"),
        @Json(name = "adobe_analytics") adobe_analytics("adobe_analytics"),
        @Json(name = "matomo") matomo("matomo"),
        @Json(name = "posthog") posthog("posthog"),
        @Json(name = "plausible") plausible("plausible"),
        @Json(name = "piano") piano("piano");
    }

}

