/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.models

import ai.llmpulse.sdk.models.WebAnalyticsQueryResponseColumnsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId 
 * @param provider 
 * @param `property` 
 * @param columns 
 * @param rows One array per row, values in column order: strings, numbers or null.
 * @param rowCount Rows in this response (at most 5,000).
 * @param totalRows Rows the provider has for the query, when it reports it.
 * @param truncated True when the provider has more rows than returned; page with its own offset or page field.
 * @param totals Metric totals by metric name, when the query asked for them.
 * @param notes Provider caveats: sampling, thresholds, more rows available.
 * @param meta Provider metadata such as GA4 time zone, currency and remaining property quota.
 * @param fetchedAt When the provider answered.
 * @param cached True when the answer came from the 10-minute cache instead of the provider.
 * @param query The request as sent to the provider, with the connected property forced and limits applied.
 * @param requestId 
 */


data class WebAnalyticsQueryResponse (

    @Json(name = "project_id")
    val projectId: kotlin.Int? = null,

    @Json(name = "provider")
    val provider: WebAnalyticsQueryResponse.Provider? = null,

    @Json(name = "property")
    val `property`: kotlin.String? = null,

    @Json(name = "columns")
    val columns: kotlin.collections.List<WebAnalyticsQueryResponseColumnsInner>? = null,

    /* One array per row, values in column order: strings, numbers or null. */
    @Json(name = "rows")
    val rows: kotlin.collections.List<kotlin.collections.List<kotlin.Any>>? = null,

    /* Rows in this response (at most 5,000). */
    @Json(name = "row_count")
    val rowCount: kotlin.Int? = null,

    /* Rows the provider has for the query, when it reports it. */
    @Json(name = "total_rows")
    val totalRows: kotlin.Int? = null,

    /* True when the provider has more rows than returned; page with its own offset or page field. */
    @Json(name = "truncated")
    val truncated: kotlin.Boolean? = null,

    /* Metric totals by metric name, when the query asked for them. */
    @Json(name = "totals")
    val totals: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Provider caveats: sampling, thresholds, more rows available. */
    @Json(name = "notes")
    val notes: kotlin.collections.List<kotlin.String>? = null,

    /* Provider metadata such as GA4 time zone, currency and remaining property quota. */
    @Json(name = "meta")
    val meta: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* When the provider answered. */
    @Json(name = "fetched_at")
    val fetchedAt: java.time.OffsetDateTime? = null,

    /* True when the answer came from the 10-minute cache instead of the provider. */
    @Json(name = "cached")
    val cached: kotlin.Boolean? = null,

    /* The request as sent to the provider, with the connected property forced and limits applied. */
    @Json(name = "query")
    val query: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "request_id")
    val requestId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: google_analytics,adobe_analytics,matomo,posthog,plausible,piano
     */
    @JsonClass(generateAdapter = false)
    enum class Provider(val value: kotlin.String) {
        @Json(name = "google_analytics") google_analytics("google_analytics"),
        @Json(name = "adobe_analytics") adobe_analytics("adobe_analytics"),
        @Json(name = "matomo") matomo("matomo"),
        @Json(name = "posthog") posthog("posthog"),
        @Json(name = "plausible") plausible("plausible"),
        @Json(name = "piano") piano("piano");
    }

}

