/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.llmpulse.sdk.models.GetTimeseriesCollectionIdParameter

import com.squareup.moshi.Json

import ai.llmpulse.sdk.infrastructure.ApiClient
import ai.llmpulse.sdk.infrastructure.ApiResponse
import ai.llmpulse.sdk.infrastructure.ClientException
import ai.llmpulse.sdk.infrastructure.ClientError
import ai.llmpulse.sdk.infrastructure.ServerException
import ai.llmpulse.sdk.infrastructure.ServerError
import ai.llmpulse.sdk.infrastructure.MultiValueMap
import ai.llmpulse.sdk.infrastructure.PartConfig
import ai.llmpulse.sdk.infrastructure.RequestConfig
import ai.llmpulse.sdk.infrastructure.RequestMethod
import ai.llmpulse.sdk.infrastructure.ResponseType
import ai.llmpulse.sdk.infrastructure.Success
import ai.llmpulse.sdk.infrastructure.toMultiValue

open class AIModelInsightsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.llmpulse.ai/api/v1")
        }
    }

    /**
     * enum for parameter granularity
     */
     enum class GranularityGetAiModelInsightsSummary(val value: kotlin.String) {
         @Json(name = "day") day("day"),
         @Json(name = "week") week("week"),
         @Json(name = "month") month("month");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter brandKind
     */
     enum class BrandKindGetAiModelInsightsSummary(val value: kotlin.String) {
         @Json(name = "brand") brand("brand"),
         @Json(name = "brand_other") brand_other("brand_other"),
         @Json(name = "non_brand") non_brand("non_brand");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /reports/ai_model_insights/summary
     * AI Model Insights summary
     * Per-model mentions, citations, brand net sentiment with raw counts, weighted visibility totals/shares, plus actor matrices. All actor entries use the standard shape &#x60;{ type, id, competitor_id, name, domain }&#x60; with bare (scheme-less) domains.
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getAiModelInsightsSummary(projectId: kotlin.Int, range: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, granularity: GranularityGetAiModelInsightsSummary? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, countryCode: kotlin.String? = null, languageCode: kotlin.String? = null, promptType: kotlin.String? = null, brandKind: BrandKindGetAiModelInsightsSummary? = null, competitors: kotlin.String? = null) : Unit {
        val localVarResponse = getAiModelInsightsSummaryWithHttpInfo(projectId = projectId, range = range, from = from, to = to, granularity = granularity, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, promptType = promptType, brandKind = brandKind, competitors = competitors)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /reports/ai_model_insights/summary
     * AI Model Insights summary
     * Per-model mentions, citations, brand net sentiment with raw counts, weighted visibility totals/shares, plus actor matrices. All actor entries use the standard shape &#x60;{ type, id, competitor_id, name, domain }&#x60; with bare (scheme-less) domains.
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun getAiModelInsightsSummaryWithHttpInfo(projectId: kotlin.Int, range: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, granularity: GranularityGetAiModelInsightsSummary?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, promptType: kotlin.String?, brandKind: BrandKindGetAiModelInsightsSummary?, competitors: kotlin.String?) : ApiResponse<Unit?> {
        val localVariableConfig = getAiModelInsightsSummaryRequestConfig(projectId = projectId, range = range, from = from, to = to, granularity = granularity, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, promptType = promptType, brandKind = brandKind, competitors = competitors)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAiModelInsightsSummary
     *
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @return RequestConfig
     */
    fun getAiModelInsightsSummaryRequestConfig(projectId: kotlin.Int, range: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, granularity: GranularityGetAiModelInsightsSummary?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, promptType: kotlin.String?, brandKind: BrandKindGetAiModelInsightsSummary?, competitors: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (range != null) {
                    put("range", listOf(range.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (granularity != null) {
                    put("granularity", listOf(granularity.value))
                }
                if (collectionId != null) {
                }
                if (countryCode != null) {
                    put("country_code", listOf(countryCode.toString()))
                }
                if (languageCode != null) {
                    put("language_code", listOf(languageCode.toString()))
                }
                if (promptType != null) {
                    put("prompt_type", listOf(promptType.toString()))
                }
                if (brandKind != null) {
                    put("brand_kind", listOf(brandKind.value))
                }
                if (competitors != null) {
                    put("competitors", listOf(competitors.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/reports/ai_model_insights/summary",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter granularity
     */
     enum class GranularityGetAiModelPositionDistribution(val value: kotlin.String) {
         @Json(name = "day") day("day"),
         @Json(name = "week") week("week"),
         @Json(name = "month") month("month");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter brandKind
     */
     enum class BrandKindGetAiModelPositionDistribution(val value: kotlin.String) {
         @Json(name = "brand") brand("brand"),
         @Json(name = "brand_other") brand_other("brand_other"),
         @Json(name = "non_brand") non_brand("non_brand");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter model
     */
     enum class ModelGetAiModelPositionDistribution(val value: kotlin.String) {
         @Json(name = "chatgpt") chatgpt("chatgpt"),
         @Json(name = "perplexity") perplexity("perplexity"),
         @Json(name = "gemini") gemini("gemini"),
         @Json(name = "ai_overview") ai_overview("ai_overview"),
         @Json(name = "ai_mode") ai_mode("ai_mode"),
         @Json(name = "copilot") copilot("copilot"),
         @Json(name = "claude") claude("claude"),
         @Json(name = "grok") grok("grok"),
         @Json(name = "deepseek") deepseek("deepseek"),
         @Json(name = "meta_ai") meta_ai("meta_ai"),
         @Json(name = "amazon_rufus") amazon_rufus("amazon_rufus"),
         @Json(name = "naver_ai") naver_ai("naver_ai"),
         @Json(name = "baidu_ai") baidu_ai("baidu_ai");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /reports/ai_model_insights/position_distribution
     * Position distribution comparison
     * 
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param brand1 Competitor ID for the first comparison brand (omit to compare project brand) (optional)
     * @param brand2  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getAiModelPositionDistribution(projectId: kotlin.Int, range: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, granularity: GranularityGetAiModelPositionDistribution? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, countryCode: kotlin.String? = null, languageCode: kotlin.String? = null, promptType: kotlin.String? = null, brandKind: BrandKindGetAiModelPositionDistribution? = null, model: ModelGetAiModelPositionDistribution? = null, brand1: kotlin.Int? = null, brand2: kotlin.Int? = null) : Unit {
        val localVarResponse = getAiModelPositionDistributionWithHttpInfo(projectId = projectId, range = range, from = from, to = to, granularity = granularity, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, promptType = promptType, brandKind = brandKind, model = model, brand1 = brand1, brand2 = brand2)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /reports/ai_model_insights/position_distribution
     * Position distribution comparison
     * 
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param brand1 Competitor ID for the first comparison brand (omit to compare project brand) (optional)
     * @param brand2  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun getAiModelPositionDistributionWithHttpInfo(projectId: kotlin.Int, range: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, granularity: GranularityGetAiModelPositionDistribution?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, promptType: kotlin.String?, brandKind: BrandKindGetAiModelPositionDistribution?, model: ModelGetAiModelPositionDistribution?, brand1: kotlin.Int?, brand2: kotlin.Int?) : ApiResponse<Unit?> {
        val localVariableConfig = getAiModelPositionDistributionRequestConfig(projectId = projectId, range = range, from = from, to = to, granularity = granularity, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, promptType = promptType, brandKind = brandKind, model = model, brand1 = brand1, brand2 = brand2)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAiModelPositionDistribution
     *
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param brand1 Competitor ID for the first comparison brand (omit to compare project brand) (optional)
     * @param brand2  (optional)
     * @return RequestConfig
     */
    fun getAiModelPositionDistributionRequestConfig(projectId: kotlin.Int, range: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, granularity: GranularityGetAiModelPositionDistribution?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, promptType: kotlin.String?, brandKind: BrandKindGetAiModelPositionDistribution?, model: ModelGetAiModelPositionDistribution?, brand1: kotlin.Int?, brand2: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (range != null) {
                    put("range", listOf(range.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (granularity != null) {
                    put("granularity", listOf(granularity.value))
                }
                if (collectionId != null) {
                }
                if (countryCode != null) {
                    put("country_code", listOf(countryCode.toString()))
                }
                if (languageCode != null) {
                    put("language_code", listOf(languageCode.toString()))
                }
                if (promptType != null) {
                    put("prompt_type", listOf(promptType.toString()))
                }
                if (brandKind != null) {
                    put("brand_kind", listOf(brandKind.value))
                }
                if (model != null) {
                    put("model", listOf(model.value))
                }
                if (brand1 != null) {
                    put("brand1", listOf(brand1.toString()))
                }
                if (brand2 != null) {
                    put("brand2", listOf(brand2.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/reports/ai_model_insights/position_distribution",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter granularity
     */
     enum class GranularityGetAiOverviewResults(val value: kotlin.String) {
         @Json(name = "day") day("day"),
         @Json(name = "week") week("week"),
         @Json(name = "month") month("month");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter brandKind
     */
     enum class BrandKindGetAiOverviewResults(val value: kotlin.String) {
         @Json(name = "brand") brand("brand"),
         @Json(name = "brand_other") brand_other("brand_other"),
         @Json(name = "non_brand") non_brand("non_brand");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /reports/ai_model_insights/ai_overview_results
     * Google AI Overview result availability
     * 
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getAiOverviewResults(projectId: kotlin.Int, range: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, granularity: GranularityGetAiOverviewResults? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, countryCode: kotlin.String? = null, languageCode: kotlin.String? = null, promptType: kotlin.String? = null, brandKind: BrandKindGetAiOverviewResults? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20) : Unit {
        val localVarResponse = getAiOverviewResultsWithHttpInfo(projectId = projectId, range = range, from = from, to = to, granularity = granularity, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, promptType = promptType, brandKind = brandKind, page = page, perPage = perPage)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /reports/ai_model_insights/ai_overview_results
     * Google AI Overview result availability
     * 
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun getAiOverviewResultsWithHttpInfo(projectId: kotlin.Int, range: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, granularity: GranularityGetAiOverviewResults?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, promptType: kotlin.String?, brandKind: BrandKindGetAiOverviewResults?, page: kotlin.Int?, perPage: kotlin.Int?) : ApiResponse<Unit?> {
        val localVariableConfig = getAiOverviewResultsRequestConfig(projectId = projectId, range = range, from = from, to = to, granularity = granularity, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, promptType = promptType, brandKind = brandKind, page = page, perPage = perPage)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAiOverviewResults
     *
     * @param projectId Project ID
     * @param range Number of days to look back (alternative to from/to) (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param granularity  (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param promptType One prompt type or a comma-separated list: informational, navigational, commercial, transactional (optional)
     * @param brandKind Filter by brand kind: brand (own brand/products), brand_other (competitors/other brands), non_brand (generic, no brand named). For fair 1:1 brand-vs-competitor comparisons (visibility, share of voice), use non_brand: brand-focused prompts skew results toward the brand they name. The in-app Overview page applies non_brand by default. (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @return RequestConfig
     */
    fun getAiOverviewResultsRequestConfig(projectId: kotlin.Int, range: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, granularity: GranularityGetAiOverviewResults?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, promptType: kotlin.String?, brandKind: BrandKindGetAiOverviewResults?, page: kotlin.Int?, perPage: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (range != null) {
                    put("range", listOf(range.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (granularity != null) {
                    put("granularity", listOf(granularity.value))
                }
                if (collectionId != null) {
                }
                if (countryCode != null) {
                    put("country_code", listOf(countryCode.toString()))
                }
                if (languageCode != null) {
                    put("language_code", listOf(languageCode.toString()))
                }
                if (promptType != null) {
                    put("prompt_type", listOf(promptType.toString()))
                }
                if (brandKind != null) {
                    put("brand_kind", listOf(brandKind.value))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/reports/ai_model_insights/ai_overview_results",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
