/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.llmpulse.sdk.models.ApiError
import ai.llmpulse.sdk.models.CreateCollectionRequest
import ai.llmpulse.sdk.models.UpdateCollectionRequest

import com.squareup.moshi.Json

import ai.llmpulse.sdk.infrastructure.ApiClient
import ai.llmpulse.sdk.infrastructure.ApiResponse
import ai.llmpulse.sdk.infrastructure.ClientException
import ai.llmpulse.sdk.infrastructure.ClientError
import ai.llmpulse.sdk.infrastructure.ServerException
import ai.llmpulse.sdk.infrastructure.ServerError
import ai.llmpulse.sdk.infrastructure.MultiValueMap
import ai.llmpulse.sdk.infrastructure.PartConfig
import ai.llmpulse.sdk.infrastructure.RequestConfig
import ai.llmpulse.sdk.infrastructure.RequestMethod
import ai.llmpulse.sdk.infrastructure.ResponseType
import ai.llmpulse.sdk.infrastructure.Success
import ai.llmpulse.sdk.infrastructure.toMultiValue

open class CollectionsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.llmpulse.ai/api/v1")
        }
    }

    /**
     * POST /collections
     * Create a tag
     * Creates a tag (Collection) in a project. Optional &#x60;prompt_ids&#x60; attaches existing prompts in the same call. Tag name must be unique per project (case-insensitive). Requires a &#x60;read_write&#x60; scope API key.
     * @param createCollectionRequest 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createCollection(createCollectionRequest: CreateCollectionRequest) : Unit {
        val localVarResponse = createCollectionWithHttpInfo(createCollectionRequest = createCollectionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /collections
     * Create a tag
     * Creates a tag (Collection) in a project. Optional &#x60;prompt_ids&#x60; attaches existing prompts in the same call. Tag name must be unique per project (case-insensitive). Requires a &#x60;read_write&#x60; scope API key.
     * @param createCollectionRequest 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun createCollectionWithHttpInfo(createCollectionRequest: CreateCollectionRequest) : ApiResponse<Unit?> {
        val localVariableConfig = createCollectionRequestConfig(createCollectionRequest = createCollectionRequest)

        return request<CreateCollectionRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createCollection
     *
     * @param createCollectionRequest 
     * @return RequestConfig
     */
    fun createCollectionRequestConfig(createCollectionRequest: CreateCollectionRequest) : RequestConfig<CreateCollectionRequest> {
        val localVariableBody = createCollectionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/collections",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /collections/{id}
     * Delete a tag
     * Deletes a tag/collection. The prompts inside it are NOT deleted; only the grouping disappears. Requires a &#x60;read_write&#x60; scope API key.
     * @param id 
     * @param projectId Project ID
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteCollection(id: kotlin.Int, projectId: kotlin.Int) : Unit {
        val localVarResponse = deleteCollectionWithHttpInfo(id = id, projectId = projectId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /collections/{id}
     * Delete a tag
     * Deletes a tag/collection. The prompts inside it are NOT deleted; only the grouping disappears. Requires a &#x60;read_write&#x60; scope API key.
     * @param id 
     * @param projectId Project ID
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteCollectionWithHttpInfo(id: kotlin.Int, projectId: kotlin.Int) : ApiResponse<Unit?> {
        val localVariableConfig = deleteCollectionRequestConfig(id = id, projectId = projectId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteCollection
     *
     * @param id 
     * @param projectId Project ID
     * @return RequestConfig
     */
    fun deleteCollectionRequestConfig(id: kotlin.Int, projectId: kotlin.Int) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/collections/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /collections/{id}
     * Update a tag
     * Renames a tag/collection or changes its description. Prompt membership is managed via POST /prompts/assign_tags, not here. Requires a &#x60;read_write&#x60; scope API key.
     * @param id 
     * @param updateCollectionRequest 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateCollection(id: kotlin.Int, updateCollectionRequest: UpdateCollectionRequest) : Unit {
        val localVarResponse = updateCollectionWithHttpInfo(id = id, updateCollectionRequest = updateCollectionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /collections/{id}
     * Update a tag
     * Renames a tag/collection or changes its description. Prompt membership is managed via POST /prompts/assign_tags, not here. Requires a &#x60;read_write&#x60; scope API key.
     * @param id 
     * @param updateCollectionRequest 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun updateCollectionWithHttpInfo(id: kotlin.Int, updateCollectionRequest: UpdateCollectionRequest) : ApiResponse<Unit?> {
        val localVariableConfig = updateCollectionRequestConfig(id = id, updateCollectionRequest = updateCollectionRequest)

        return request<UpdateCollectionRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateCollection
     *
     * @param id 
     * @param updateCollectionRequest 
     * @return RequestConfig
     */
    fun updateCollectionRequestConfig(id: kotlin.Int, updateCollectionRequest: UpdateCollectionRequest) : RequestConfig<UpdateCollectionRequest> {
        val localVariableBody = updateCollectionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/collections/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
