/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.llmpulse.sdk.models.GetTimeseriesCollectionIdParameter

import com.squareup.moshi.Json

import ai.llmpulse.sdk.infrastructure.ApiClient
import ai.llmpulse.sdk.infrastructure.ApiResponse
import ai.llmpulse.sdk.infrastructure.ClientException
import ai.llmpulse.sdk.infrastructure.ClientError
import ai.llmpulse.sdk.infrastructure.ServerException
import ai.llmpulse.sdk.infrastructure.ServerError
import ai.llmpulse.sdk.infrastructure.MultiValueMap
import ai.llmpulse.sdk.infrastructure.PartConfig
import ai.llmpulse.sdk.infrastructure.RequestConfig
import ai.llmpulse.sdk.infrastructure.RequestMethod
import ai.llmpulse.sdk.infrastructure.ResponseType
import ai.llmpulse.sdk.infrastructure.Success
import ai.llmpulse.sdk.infrastructure.toMultiValue

open class MentionsCitationsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.llmpulse.ai/api/v1")
        }
    }

    /**
     * enum for parameter model
     */
     enum class ModelListAllCitations(val value: kotlin.String) {
         @Json(name = "chatgpt") chatgpt("chatgpt"),
         @Json(name = "perplexity") perplexity("perplexity"),
         @Json(name = "gemini") gemini("gemini"),
         @Json(name = "ai_overview") ai_overview("ai_overview"),
         @Json(name = "ai_mode") ai_mode("ai_mode"),
         @Json(name = "copilot") copilot("copilot"),
         @Json(name = "claude") claude("claude"),
         @Json(name = "grok") grok("grok"),
         @Json(name = "deepseek") deepseek("deepseek"),
         @Json(name = "meta_ai") meta_ai("meta_ai"),
         @Json(name = "amazon_rufus") amazon_rufus("amazon_rufus"),
         @Json(name = "naver_ai") naver_ai("naver_ai"),
         @Json(name = "baidu_ai") baidu_ai("baidu_ai");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter output
     */
     enum class OutputListAllCitations(val value: kotlin.String) {
         @Json(name = "flat") flat("flat"),
         @Json(name = "csv") csv("csv");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /dimensions/all_citations
     * List all citations (brand + competitor)
     * Unified citations stream with an &#x60;actor_type&#x60; field on each record. Includes visible citations and background source references; background references use position 0, meaning no visible rank.
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listAllCitations(projectId: kotlin.Int, competitors: kotlin.String? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, model: ModelListAllCitations? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, prompt: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, output: OutputListAllCitations? = null) : Unit {
        val localVarResponse = listAllCitationsWithHttpInfo(projectId = projectId, competitors = competitors, page = page, perPage = perPage, model = model, collectionId = collectionId, prompt = prompt, from = from, to = to, output = output)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /dimensions/all_citations
     * List all citations (brand + competitor)
     * Unified citations stream with an &#x60;actor_type&#x60; field on each record. Includes visible citations and background source references; background references use position 0, meaning no visible rank.
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun listAllCitationsWithHttpInfo(projectId: kotlin.Int, competitors: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListAllCitations?, collectionId: GetTimeseriesCollectionIdParameter?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListAllCitations?) : ApiResponse<Unit?> {
        val localVariableConfig = listAllCitationsRequestConfig(projectId = projectId, competitors = competitors, page = page, perPage = perPage, model = model, collectionId = collectionId, prompt = prompt, from = from, to = to, output = output)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAllCitations
     *
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return RequestConfig
     */
    fun listAllCitationsRequestConfig(projectId: kotlin.Int, competitors: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListAllCitations?, collectionId: GetTimeseriesCollectionIdParameter?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListAllCitations?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (competitors != null) {
                    put("competitors", listOf(competitors.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (model != null) {
                    put("model", listOf(model.value))
                }
                if (collectionId != null) {
                }
                if (prompt != null) {
                    put("prompt", listOf(prompt.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (output != null) {
                    put("output", listOf(output.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/dimensions/all_citations",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter model
     */
     enum class ModelListAllMentions(val value: kotlin.String) {
         @Json(name = "chatgpt") chatgpt("chatgpt"),
         @Json(name = "perplexity") perplexity("perplexity"),
         @Json(name = "gemini") gemini("gemini"),
         @Json(name = "ai_overview") ai_overview("ai_overview"),
         @Json(name = "ai_mode") ai_mode("ai_mode"),
         @Json(name = "copilot") copilot("copilot"),
         @Json(name = "claude") claude("claude"),
         @Json(name = "grok") grok("grok"),
         @Json(name = "deepseek") deepseek("deepseek"),
         @Json(name = "meta_ai") meta_ai("meta_ai"),
         @Json(name = "amazon_rufus") amazon_rufus("amazon_rufus"),
         @Json(name = "naver_ai") naver_ai("naver_ai"),
         @Json(name = "baidu_ai") baidu_ai("baidu_ai");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter output
     */
     enum class OutputListAllMentions(val value: kotlin.String) {
         @Json(name = "flat") flat("flat"),
         @Json(name = "csv") csv("csv");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /dimensions/all_mentions
     * List all mentions (brand + competitor)
     * Unified mentions stream. Each record has an &#x60;actor_type&#x60; field (&#x60;project&#x60; or &#x60;competitor&#x60;) so the same payload covers both.
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listAllMentions(projectId: kotlin.Int, competitors: kotlin.String? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, model: ModelListAllMentions? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, prompt: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, output: OutputListAllMentions? = null) : Unit {
        val localVarResponse = listAllMentionsWithHttpInfo(projectId = projectId, competitors = competitors, page = page, perPage = perPage, model = model, collectionId = collectionId, prompt = prompt, from = from, to = to, output = output)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /dimensions/all_mentions
     * List all mentions (brand + competitor)
     * Unified mentions stream. Each record has an &#x60;actor_type&#x60; field (&#x60;project&#x60; or &#x60;competitor&#x60;) so the same payload covers both.
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun listAllMentionsWithHttpInfo(projectId: kotlin.Int, competitors: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListAllMentions?, collectionId: GetTimeseriesCollectionIdParameter?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListAllMentions?) : ApiResponse<Unit?> {
        val localVariableConfig = listAllMentionsRequestConfig(projectId = projectId, competitors = competitors, page = page, perPage = perPage, model = model, collectionId = collectionId, prompt = prompt, from = from, to = to, output = output)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAllMentions
     *
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return RequestConfig
     */
    fun listAllMentionsRequestConfig(projectId: kotlin.Int, competitors: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListAllMentions?, collectionId: GetTimeseriesCollectionIdParameter?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListAllMentions?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (competitors != null) {
                    put("competitors", listOf(competitors.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (model != null) {
                    put("model", listOf(model.value))
                }
                if (collectionId != null) {
                }
                if (prompt != null) {
                    put("prompt", listOf(prompt.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (output != null) {
                    put("output", listOf(output.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/dimensions/all_mentions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter model
     */
     enum class ModelListCitations(val value: kotlin.String) {
         @Json(name = "chatgpt") chatgpt("chatgpt"),
         @Json(name = "perplexity") perplexity("perplexity"),
         @Json(name = "gemini") gemini("gemini"),
         @Json(name = "ai_overview") ai_overview("ai_overview"),
         @Json(name = "ai_mode") ai_mode("ai_mode"),
         @Json(name = "copilot") copilot("copilot"),
         @Json(name = "claude") claude("claude"),
         @Json(name = "grok") grok("grok"),
         @Json(name = "deepseek") deepseek("deepseek"),
         @Json(name = "meta_ai") meta_ai("meta_ai"),
         @Json(name = "amazon_rufus") amazon_rufus("amazon_rufus"),
         @Json(name = "naver_ai") naver_ai("naver_ai"),
         @Json(name = "baidu_ai") baidu_ai("baidu_ai");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter output
     */
     enum class OutputListCitations(val value: kotlin.String) {
         @Json(name = "flat") flat("flat"),
         @Json(name = "csv") csv("csv");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /dimensions/citations
     * List brand citations
     * Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
     * @param projectId Project ID
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listCitations(projectId: kotlin.Int, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, model: ModelListCitations? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, countryCode: kotlin.String? = null, languageCode: kotlin.String? = null, prompt: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, output: OutputListCitations? = null) : Unit {
        val localVarResponse = listCitationsWithHttpInfo(projectId = projectId, page = page, perPage = perPage, model = model, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, prompt = prompt, from = from, to = to, output = output)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /dimensions/citations
     * List brand citations
     * Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
     * @param projectId Project ID
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun listCitationsWithHttpInfo(projectId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListCitations?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListCitations?) : ApiResponse<Unit?> {
        val localVariableConfig = listCitationsRequestConfig(projectId = projectId, page = page, perPage = perPage, model = model, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, prompt = prompt, from = from, to = to, output = output)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listCitations
     *
     * @param projectId Project ID
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return RequestConfig
     */
    fun listCitationsRequestConfig(projectId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListCitations?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListCitations?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (model != null) {
                    put("model", listOf(model.value))
                }
                if (collectionId != null) {
                }
                if (countryCode != null) {
                    put("country_code", listOf(countryCode.toString()))
                }
                if (languageCode != null) {
                    put("language_code", listOf(languageCode.toString()))
                }
                if (prompt != null) {
                    put("prompt", listOf(prompt.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (output != null) {
                    put("output", listOf(output.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/dimensions/citations",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter model
     */
     enum class ModelListCompetitorCitations(val value: kotlin.String) {
         @Json(name = "chatgpt") chatgpt("chatgpt"),
         @Json(name = "perplexity") perplexity("perplexity"),
         @Json(name = "gemini") gemini("gemini"),
         @Json(name = "ai_overview") ai_overview("ai_overview"),
         @Json(name = "ai_mode") ai_mode("ai_mode"),
         @Json(name = "copilot") copilot("copilot"),
         @Json(name = "claude") claude("claude"),
         @Json(name = "grok") grok("grok"),
         @Json(name = "deepseek") deepseek("deepseek"),
         @Json(name = "meta_ai") meta_ai("meta_ai"),
         @Json(name = "amazon_rufus") amazon_rufus("amazon_rufus"),
         @Json(name = "naver_ai") naver_ai("naver_ai"),
         @Json(name = "baidu_ai") baidu_ai("baidu_ai");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter output
     */
     enum class OutputListCompetitorCitations(val value: kotlin.String) {
         @Json(name = "flat") flat("flat"),
         @Json(name = "csv") csv("csv");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /dimensions/competitor_citations
     * List competitor citations
     * Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listCompetitorCitations(projectId: kotlin.Int, competitors: kotlin.String? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, model: ModelListCompetitorCitations? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, prompt: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, output: OutputListCompetitorCitations? = null) : Unit {
        val localVarResponse = listCompetitorCitationsWithHttpInfo(projectId = projectId, competitors = competitors, page = page, perPage = perPage, model = model, collectionId = collectionId, prompt = prompt, from = from, to = to, output = output)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /dimensions/competitor_citations
     * List competitor citations
     * Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun listCompetitorCitationsWithHttpInfo(projectId: kotlin.Int, competitors: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListCompetitorCitations?, collectionId: GetTimeseriesCollectionIdParameter?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListCompetitorCitations?) : ApiResponse<Unit?> {
        val localVariableConfig = listCompetitorCitationsRequestConfig(projectId = projectId, competitors = competitors, page = page, perPage = perPage, model = model, collectionId = collectionId, prompt = prompt, from = from, to = to, output = output)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listCompetitorCitations
     *
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return RequestConfig
     */
    fun listCompetitorCitationsRequestConfig(projectId: kotlin.Int, competitors: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListCompetitorCitations?, collectionId: GetTimeseriesCollectionIdParameter?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListCompetitorCitations?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (competitors != null) {
                    put("competitors", listOf(competitors.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (model != null) {
                    put("model", listOf(model.value))
                }
                if (collectionId != null) {
                }
                if (prompt != null) {
                    put("prompt", listOf(prompt.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (output != null) {
                    put("output", listOf(output.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/dimensions/competitor_citations",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter model
     */
     enum class ModelListCompetitorMentions(val value: kotlin.String) {
         @Json(name = "chatgpt") chatgpt("chatgpt"),
         @Json(name = "perplexity") perplexity("perplexity"),
         @Json(name = "gemini") gemini("gemini"),
         @Json(name = "ai_overview") ai_overview("ai_overview"),
         @Json(name = "ai_mode") ai_mode("ai_mode"),
         @Json(name = "copilot") copilot("copilot"),
         @Json(name = "claude") claude("claude"),
         @Json(name = "grok") grok("grok"),
         @Json(name = "deepseek") deepseek("deepseek"),
         @Json(name = "meta_ai") meta_ai("meta_ai"),
         @Json(name = "amazon_rufus") amazon_rufus("amazon_rufus"),
         @Json(name = "naver_ai") naver_ai("naver_ai"),
         @Json(name = "baidu_ai") baidu_ai("baidu_ai");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter output
     */
     enum class OutputListCompetitorMentions(val value: kotlin.String) {
         @Json(name = "flat") flat("flat"),
         @Json(name = "csv") csv("csv");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /dimensions/competitor_mentions
     * List competitor mentions
     * 
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listCompetitorMentions(projectId: kotlin.Int, competitors: kotlin.String? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, model: ModelListCompetitorMentions? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, prompt: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, output: OutputListCompetitorMentions? = null) : Unit {
        val localVarResponse = listCompetitorMentionsWithHttpInfo(projectId = projectId, competitors = competitors, page = page, perPage = perPage, model = model, collectionId = collectionId, prompt = prompt, from = from, to = to, output = output)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /dimensions/competitor_mentions
     * List competitor mentions
     * 
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun listCompetitorMentionsWithHttpInfo(projectId: kotlin.Int, competitors: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListCompetitorMentions?, collectionId: GetTimeseriesCollectionIdParameter?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListCompetitorMentions?) : ApiResponse<Unit?> {
        val localVariableConfig = listCompetitorMentionsRequestConfig(projectId = projectId, competitors = competitors, page = page, perPage = perPage, model = model, collectionId = collectionId, prompt = prompt, from = from, to = to, output = output)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listCompetitorMentions
     *
     * @param projectId Project ID
     * @param competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM) (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return RequestConfig
     */
    fun listCompetitorMentionsRequestConfig(projectId: kotlin.Int, competitors: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListCompetitorMentions?, collectionId: GetTimeseriesCollectionIdParameter?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListCompetitorMentions?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (competitors != null) {
                    put("competitors", listOf(competitors.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (model != null) {
                    put("model", listOf(model.value))
                }
                if (collectionId != null) {
                }
                if (prompt != null) {
                    put("prompt", listOf(prompt.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (output != null) {
                    put("output", listOf(output.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/dimensions/competitor_mentions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter model
     */
     enum class ModelListMentions(val value: kotlin.String) {
         @Json(name = "chatgpt") chatgpt("chatgpt"),
         @Json(name = "perplexity") perplexity("perplexity"),
         @Json(name = "gemini") gemini("gemini"),
         @Json(name = "ai_overview") ai_overview("ai_overview"),
         @Json(name = "ai_mode") ai_mode("ai_mode"),
         @Json(name = "copilot") copilot("copilot"),
         @Json(name = "claude") claude("claude"),
         @Json(name = "grok") grok("grok"),
         @Json(name = "deepseek") deepseek("deepseek"),
         @Json(name = "meta_ai") meta_ai("meta_ai"),
         @Json(name = "amazon_rufus") amazon_rufus("amazon_rufus"),
         @Json(name = "naver_ai") naver_ai("naver_ai"),
         @Json(name = "baidu_ai") baidu_ai("baidu_ai");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * enum for parameter output
     */
     enum class OutputListMentions(val value: kotlin.String) {
         @Json(name = "flat") flat("flat"),
         @Json(name = "csv") csv("csv");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /dimensions/mentions
     * List brand mentions
     * 
     * @param projectId Project ID
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listMentions(projectId: kotlin.Int, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20, model: ModelListMentions? = null, collectionId: GetTimeseriesCollectionIdParameter? = null, countryCode: kotlin.String? = null, languageCode: kotlin.String? = null, prompt: kotlin.Int? = null, from: java.time.OffsetDateTime? = null, to: java.time.OffsetDateTime? = null, output: OutputListMentions? = null) : Unit {
        val localVarResponse = listMentionsWithHttpInfo(projectId = projectId, page = page, perPage = perPage, model = model, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, prompt = prompt, from = from, to = to, output = output)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /dimensions/mentions
     * List brand mentions
     * 
     * @param projectId Project ID
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun listMentionsWithHttpInfo(projectId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListMentions?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListMentions?) : ApiResponse<Unit?> {
        val localVariableConfig = listMentionsRequestConfig(projectId = projectId, page = page, perPage = perPage, model = model, collectionId = collectionId, countryCode = countryCode, languageCode = languageCode, prompt = prompt, from = from, to = to, output = output)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listMentions
     *
     * @param projectId Project ID
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @param model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped. (optional)
     * @param collectionId One collection/tag ID or a comma-separated list of IDs (optional)
     * @param countryCode One ISO country code or a comma-separated list (e.g. US,GB,DE) (optional)
     * @param languageCode One ISO language code or a comma-separated list (e.g. en,es,de) (optional)
     * @param prompt Filter by prompt ID (optional)
     * @param from  (optional)
     * @param to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier. (optional)
     * @param output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON. (optional)
     * @return RequestConfig
     */
    fun listMentionsRequestConfig(projectId: kotlin.Int, page: kotlin.Int?, perPage: kotlin.Int?, model: ModelListMentions?, collectionId: GetTimeseriesCollectionIdParameter?, countryCode: kotlin.String?, languageCode: kotlin.String?, prompt: kotlin.Int?, from: java.time.OffsetDateTime?, to: java.time.OffsetDateTime?, output: OutputListMentions?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (model != null) {
                    put("model", listOf(model.value))
                }
                if (collectionId != null) {
                }
                if (countryCode != null) {
                    put("country_code", listOf(countryCode.toString()))
                }
                if (languageCode != null) {
                    put("language_code", listOf(languageCode.toString()))
                }
                if (prompt != null) {
                    put("prompt", listOf(prompt.toString()))
                }
                if (from != null) {
                    put("from", listOf(parseDateToQueryString<java.time.OffsetDateTime>(from)))
                }
                if (to != null) {
                    put("to", listOf(parseDateToQueryString<java.time.OffsetDateTime>(to)))
                }
                if (output != null) {
                    put("output", listOf(output.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/dimensions/mentions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
