/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.llmpulse.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.llmpulse.sdk.models.ApiError
import ai.llmpulse.sdk.models.CreateTechnicalGeoReportsRequest

import com.squareup.moshi.Json

import ai.llmpulse.sdk.infrastructure.ApiClient
import ai.llmpulse.sdk.infrastructure.ApiResponse
import ai.llmpulse.sdk.infrastructure.ClientException
import ai.llmpulse.sdk.infrastructure.ClientError
import ai.llmpulse.sdk.infrastructure.ServerException
import ai.llmpulse.sdk.infrastructure.ServerError
import ai.llmpulse.sdk.infrastructure.MultiValueMap
import ai.llmpulse.sdk.infrastructure.PartConfig
import ai.llmpulse.sdk.infrastructure.RequestConfig
import ai.llmpulse.sdk.infrastructure.RequestMethod
import ai.llmpulse.sdk.infrastructure.ResponseType
import ai.llmpulse.sdk.infrastructure.Success
import ai.llmpulse.sdk.infrastructure.toMultiValue

open class TechnicalGEOReportsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.llmpulse.ai/api/v1")
        }
    }

    /**
     * POST /technical_geo_reports
     * Run technical GEO analysis
     * Launches the full technical GEO analysis bundle (crawlability, schema, content readiness, discoverability, site structure, robots.txt, agent readiness, llms.txt, AI visibility) for a URL + country. Each report runs in a background job. Requires a &#x60;read_write&#x60; scope API key.
     * @param createTechnicalGeoReportsRequest 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createTechnicalGeoReports(createTechnicalGeoReportsRequest: CreateTechnicalGeoReportsRequest) : Unit {
        val localVarResponse = createTechnicalGeoReportsWithHttpInfo(createTechnicalGeoReportsRequest = createTechnicalGeoReportsRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /technical_geo_reports
     * Run technical GEO analysis
     * Launches the full technical GEO analysis bundle (crawlability, schema, content readiness, discoverability, site structure, robots.txt, agent readiness, llms.txt, AI visibility) for a URL + country. Each report runs in a background job. Requires a &#x60;read_write&#x60; scope API key.
     * @param createTechnicalGeoReportsRequest 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun createTechnicalGeoReportsWithHttpInfo(createTechnicalGeoReportsRequest: CreateTechnicalGeoReportsRequest) : ApiResponse<Unit?> {
        val localVariableConfig = createTechnicalGeoReportsRequestConfig(createTechnicalGeoReportsRequest = createTechnicalGeoReportsRequest)

        return request<CreateTechnicalGeoReportsRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createTechnicalGeoReports
     *
     * @param createTechnicalGeoReportsRequest 
     * @return RequestConfig
     */
    fun createTechnicalGeoReportsRequestConfig(createTechnicalGeoReportsRequest: CreateTechnicalGeoReportsRequest) : RequestConfig<CreateTechnicalGeoReportsRequest> {
        val localVariableBody = createTechnicalGeoReportsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/technical_geo_reports",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter reportType
     */
     enum class ReportTypeGetTechnicalGeoReport(val value: kotlin.String) {
         @Json(name = "crawlability") crawlability("crawlability"),
         @Json(name = "schema") schema("schema"),
         @Json(name = "content_readiness") content_readiness("content_readiness"),
         @Json(name = "discoverability") discoverability("discoverability"),
         @Json(name = "site_structure") site_structure("site_structure"),
         @Json(name = "robots_txt") robots_txt("robots_txt"),
         @Json(name = "agent_readiness") agent_readiness("agent_readiness"),
         @Json(name = "llms_txt") llms_txt("llms_txt"),
         @Json(name = "ai_visibility") ai_visibility("ai_visibility");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /technical_geo_reports/{id}
     * Get a technical GEO report
     * Returns the current status and the full result_data once the report is completed. While it is running, result_data is null and poll_after_seconds tells clients when to check again.
     * @param id Report id returned by POST /technical_geo_reports or GET /technical_geo_reports
     * @param projectId Project ID
     * @param reportType 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getTechnicalGeoReport(id: kotlin.Int, projectId: kotlin.Int, reportType: ReportTypeGetTechnicalGeoReport) : Unit {
        val localVarResponse = getTechnicalGeoReportWithHttpInfo(id = id, projectId = projectId, reportType = reportType)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /technical_geo_reports/{id}
     * Get a technical GEO report
     * Returns the current status and the full result_data once the report is completed. While it is running, result_data is null and poll_after_seconds tells clients when to check again.
     * @param id Report id returned by POST /technical_geo_reports or GET /technical_geo_reports
     * @param projectId Project ID
     * @param reportType 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun getTechnicalGeoReportWithHttpInfo(id: kotlin.Int, projectId: kotlin.Int, reportType: ReportTypeGetTechnicalGeoReport) : ApiResponse<Unit?> {
        val localVariableConfig = getTechnicalGeoReportRequestConfig(id = id, projectId = projectId, reportType = reportType)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getTechnicalGeoReport
     *
     * @param id Report id returned by POST /technical_geo_reports or GET /technical_geo_reports
     * @param projectId Project ID
     * @param reportType 
     * @return RequestConfig
     */
    fun getTechnicalGeoReportRequestConfig(id: kotlin.Int, projectId: kotlin.Int, reportType: ReportTypeGetTechnicalGeoReport) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                put("report_type", listOf(reportType.value))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/technical_geo_reports/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter reportType
     */
     enum class ReportTypeListTechnicalGeoReports(val value: kotlin.String) {
         @Json(name = "crawlability") crawlability("crawlability"),
         @Json(name = "schema") schema("schema"),
         @Json(name = "content_readiness") content_readiness("content_readiness"),
         @Json(name = "discoverability") discoverability("discoverability"),
         @Json(name = "site_structure") site_structure("site_structure"),
         @Json(name = "robots_txt") robots_txt("robots_txt"),
         @Json(name = "agent_readiness") agent_readiness("agent_readiness"),
         @Json(name = "llms_txt") llms_txt("llms_txt"),
         @Json(name = "ai_visibility") ai_visibility("ai_visibility");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * GET /technical_geo_reports
     * List technical GEO reports
     * Lists reports of one technical GEO type for a project, newest first. Use agent_readiness for the AI/Agent Readiness report.
     * @param projectId Project ID
     * @param reportType 
     * @param status Optional status filter; valid values depend on report_type (optional)
     * @param batchId Optional batch id returned when the report bundle was created (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listTechnicalGeoReports(projectId: kotlin.Int, reportType: ReportTypeListTechnicalGeoReports, status: kotlin.String? = null, batchId: kotlin.Int? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = 20) : Unit {
        val localVarResponse = listTechnicalGeoReportsWithHttpInfo(projectId = projectId, reportType = reportType, status = status, batchId = batchId, page = page, perPage = perPage)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /technical_geo_reports
     * List technical GEO reports
     * Lists reports of one technical GEO type for a project, newest first. Use agent_readiness for the AI/Agent Readiness report.
     * @param projectId Project ID
     * @param reportType 
     * @param status Optional status filter; valid values depend on report_type (optional)
     * @param batchId Optional batch id returned when the report bundle was created (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun listTechnicalGeoReportsWithHttpInfo(projectId: kotlin.Int, reportType: ReportTypeListTechnicalGeoReports, status: kotlin.String?, batchId: kotlin.Int?, page: kotlin.Int?, perPage: kotlin.Int?) : ApiResponse<Unit?> {
        val localVariableConfig = listTechnicalGeoReportsRequestConfig(projectId = projectId, reportType = reportType, status = status, batchId = batchId, page = page, perPage = perPage)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listTechnicalGeoReports
     *
     * @param projectId Project ID
     * @param reportType 
     * @param status Optional status filter; valid values depend on report_type (optional)
     * @param batchId Optional batch id returned when the report bundle was created (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 20)
     * @return RequestConfig
     */
    fun listTechnicalGeoReportsRequestConfig(projectId: kotlin.Int, reportType: ReportTypeListTechnicalGeoReports, status: kotlin.String?, batchId: kotlin.Int?, page: kotlin.Int?, perPage: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("project_id", listOf(projectId.toString()))
                put("report_type", listOf(reportType.value))
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
                if (batchId != null) {
                    put("batch_id", listOf(batchId.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/technical_geo_reports",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
